# Generated by Django 2.2.3 on 2019-07-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190724_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='Co chcesz napisać?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='overview',
            field=models.TextField(max_length=300),
        ),
    ]
