# Generated by Django 2.2.3 on 2019-07-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='car_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
