# Generated by Django 2.2.3 on 2019-07-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_shop_car_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='gridbox',
            field=models.CharField(max_length=20),
        ),
    ]
